# Generated by Django 4.2.4 on 2023-08-24 13:52

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouqet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание букета')),
                ('image', models.ImageField(null=True, upload_to='images', verbose_name='Фото букета')),
            ],
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название цветка')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Повод')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('tg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', verbose_name='Номер клиента')),
                ('role', models.CharField(choices=[('C', 'Client'), ('D', 'Delivery man'), ('F', 'Florist')], default='C', max_length=12, verbose_name='Роль пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя получателя')),
                ('delivery_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес доставки')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата доставки')),
                ('delivery_time', models.TimeField(blank=True, null=True, verbose_name='Время доставки')),
                ('status', models.CharField(choices=[('P', 'Placed'), ('W', 'Waiting for call'), ('D', 'Delivered')], max_length=16, verbose_name='Статус заказа')),
                ('bouqet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderes', to='flowershop_bot.bouqet', verbose_name='Букет в заказе')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='flowershop_bot.user', verbose_name='Пользователи')),
            ],
        ),
        migrations.AddField(
            model_name='bouqet',
            name='flowers',
            field=models.ManyToManyField(db_index=True, related_name='bouqets', to='flowershop_bot.flower', verbose_name='Цветы в букете'),
        ),
        migrations.AddField(
            model_name='bouqet',
            name='occasion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouqets', to='flowershop_bot.occasion', verbose_name='Повод букета'),
        ),
    ]
